### ISSUE TITLE
Better names for Tiles

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#139]
The name "tile" is used in several different contexts, which could be confusing. Currently "Tile" is used to describe:
- An (x, y) location on a map
- A data structure describing the graphic and animation of the above, from the set of all tilesets
- A graphical representation within a single tile set.

Similarly, "tileIndex" is used in all 3 contexts, making it harder to tell what the value actually represents.

We should rename some variables to make a better distinction between these cases. Currently using "TileData" versus "TileInfo" just doesn't explain the difference.

Example code:
https://github.com/OutpostUniverse/OP2Utility/blob/0a8389e532cbe21193c1b654b6036c2695e0affa/src/Maps/MapData.h#L28-L52

**Comment by Brett208** [comment]
Maybe a preference choice, but I would like to see MapData::numTilesets renamed to tilesetCount. 

This issue is actually really important for usability of the MapData class by others.

**Comment by Brett208** [comment]
What if we just drop data from TileData. Then it would be Tile and TileMapping. Where Tile is the primary structure describing an individual Tile. TileMapping contains the global properties attached to the tile. This seems a lot better to me, although maybe still room for improvement?

I like that we both came to the conclusion that TileData and TileInfo were poor name choices right before you read the chapter dealing with it. 

I'm split on naming MapData just Map. Map could mean a dictionary like container instead of a 2D map. We could go with OP2Map. :) @DanRStevens if you want to go with Map over MapData, I can live with that.

We have split the project between using a num prefix and a count suffix. I overall prefer the count suffix. Perhaps this is a discussion for a different issue though sense it runs deeper through the codebase than just in the Maps section.

**Comment by DanRStevens** [comment]
I'm ok with renaming `TileData` to just `Tile`. I think I can live with renaming `TileInfo` to `TileMapping`. We still need one more name though, at least for index values. Perhaps `tileGraphicIndex`.

Curiously, the book also recommended against adding gratuitous context, such as project name acronyms used as variable name prefixes. Hence "OP2Map" is not advisable.

As for name confusion, assuming we aren't using `using`, the STL container will be [`std::map`](https://en.cppreference.com/w/cpp/container/map). That's actually very much why the STL was put into the `std` namespace, to prevent name collisions from things like this. I think it's actually fine to just use `Map`. That's really the name that makes the most sense in the given context.

Perhaps a related issue, is if we want to wrap the OP2Utility API into a namespace.

As for "num" versus "Count", I'm thinking let's just go with "Count". What I don't like about "num", is it's an abbreviation. What I don't like about "Count" is it's also a verb. Granted, grammar context clears that up, and I think a dual use word is better than an abbreviation. Another slight adjustment is pluralization on the base concept. For example "numBytes" (plural) versus "byteCount" (singular).

**Comment by Brett208** [comment]
Okay, Map instead of MapData sounds good.

I'm not sure what strategy we want to go with for namespace wrapping. I would generally like to see the code wrapped. I would generally prefer to not get carried away with too many sub-namespaces. Maybe OP2Utility could just use the namespace OP2? Then it would be OP2::Map, OP2::Tile, OP2::TileMapping.

This would make the archive code look like OP2::Archives::ClmFile. If we drop the Archives namespace, it would just be OP2::ClmFile.

Would you want the stream code also in this namespace? It would be OP2::Stream::FileReader then. I would be okay leaving the stream code outside of the global namespace, but then it really would not be a global namespace.

Thanks,
Brett

**Comment by DanRStevens** [comment]
That's a very good question to be asking. I remember reading somewhere that C++ namespaces were not a proper module system, and trying to treat them as such with deeply nested namespaces wasn't usually very helpful. I don't remember specifics as to why. For a particular example, most of the standard C++ library is in the single namespace `std`. I think the suggestion is to use a single namespace for an entire library.

As for the name, I think I would prefer "op2utility" rather than "OP2". It is just a utility library after all, and not the game itself. We should also decide on use of camel case and capitalization, including capitalization of acronyms. Though technically, OP2 isn't an acronym. If it was, it should be just O2. Curiously, I vaguely remember seeing the abbreviation "O2" listed somewhere from the original game developers.

I notice a lot of the standard C++ library methods use lowerCamelCase (aka Camel Case), while Windows API code uses UpperCamelCase (aka Pascal Case). Based on method and class names, we seem to be using largely the later. Per Microsoft recommendations on [capitalization conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions), namespaces should use Pascal Case, and acronyms should be cased like they were a word, unless they are only 2 letters. Per additional Microsoft recommendations on [capitalization conventions](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229043(v=vs.100)), abbreviations are not the same as acronyms, as they only shorten a single word, and should simply be avoided. Two listed exceptions are ID (identifier) and OK, which should be "Id" and "Ok" in Pascal Case.

I suppose we'll need an interpretation on what to do with OP2. Technically that's an abbreviation that should be avoided, though it's also extremely common at OPU.

Side note: the above two documents talk about not capitalizing each word in closed form compound words. However, it lists several common terms which are not closed form compound words, and gives the recommended casing. Curiously, "fileName" appears in that list.
