### ISSUE TITLE
HuffLZ simplifications

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#150]
I'm thinking we should simplify the `HuffLZ` constructors. We don't need to offer both a constructor accepting a `BitStreamReader` object, and a constructor accepting the raw arguments to construct a `BitStreamReader` object.

The `BitStreamReader` object is cheap to copy. It uses a shallow copy, so no need to worry about copying full data buffers. Since the constructor argument is copied, it can be `const`, allowing it to bind to temporaries. That allows for construction with inline temporaries.

Additionally, the order of the arguments is inconsistent with the Stream library design. The stream library uses the parameter order `(void* buffer, std::size_t size)`, whereas the `BitStreamReader` and `HuffLZ` object use the parameter order `(std::size_t size, void* buffer)`.

There's also some inconsistency with using `size` versus `length`. The standard C++ library tends to use `size`. Maybe we should do the same.

In regards to changes, a quick check with `grep` reveals the `HuffLZ` object is constructed in exactly one place (and it uses the unpacked parameter form):
src/Archives/VolFile.cpp:134:			
```cpp
HuffLZ decompressor(length, buffer.data());
```

Perhaps we should only construct from an explicit `BitStreamReader` object, which can be an inline temporary, which gets shallow copied into the object, re-order the parameters, and rename `lengh` to `size`:
```cpp
HuffLZ decompressor(BitStreamReader(buffer.data(), size));
```

----

It's tempting to suggest having `BitStreamReader` take a `vector` object, which has both `data` and `size`. However, I think that part of the `BitStreamReader` design was temporary in nature, and was done to aid porting. I think the longer term solution is to have `BitStreamReader` take a `StreamReader` in its constructor, rather than a raw buffer. Effectively, the `BitStreamReader` class is really just an adaptor class, which takes a stream of bytes, and serves them as a stream of bits.

This is also further reason to eliminate the extra constructor in `HuffLZ`, since construction really depends on the specifics of the source stream, of which there can be many types, some of which might be designed after this library is released.

**Comment by Brett208** [comment]
I'm happy with size instead of length. It is shorter to type and I like matching a bit closer to the standard library.

Agreed on reordering arguments to match the StreamReader.

We should probably remove the other constructor for now so in the future when we change BitStreamReader, it will match with HuffLZ without changes.

I would be happy to see BitStreamReader improved. I think I'd like to see it eventually moved into the Stream library instead of the Archive library. Maybe we should separate this issue into 2: This one for the simpler, easier updates to HuffLZ and another for BitStreamReader consume a Stream::Reader.

Thanks,
Brett

**Comment by DanRStevens** [comment]
I think I'm going to close this. All the tangible points listed here have now been merged in.
