### ISSUE TITLE
Create Stream::MemoryReader overloads to simplify reading from std library containers

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#158]
We could simplify the creation of a MemoryReader from standard library containers. Oftentimes I find myself reading from the entire container.

Maybe:
```
std::vector<int> buffer { 1, 2, 3, 4, 5 };
Stream::MemoryReader<int>(buffer);
```

I'm not 100% sold on the idea as it will increase the number of constructors significantly, but it also seems like a fairly common use case. Wanted to bring it up.

-Brett

**Comment by DanRStevens** [comment]
I'm actually in favour of doing this. It makes it easier to write test code. Generally speaking, easier to write test code usually means a better API and easier to write code. Besides, it's only 1 extra constructor, and matches what we've already done in the Streams API.

In fact, I was recently tempted to add such a constructor to the BitStreamReader.

**Comment by DanRStevens** [comment]
I was just looking back at this and noticed `<int>` was specified twice. I don't think that's necessary since the `<int>` parameter was already encoded for the `vector` type. In terms of  user code it should simply be:
```cpp
std::vector<int> buffer { 1, 2, 3, 4, 5 };
Stream::MemoryReader(buffer);
```

From within the `Stream::MemoryReader` class, the constructor would need to be templated, or would need a templated helper function that calls the constructor.

----

Just now realizing the template code from the `Stream::Reader::Read` methods won't quite work here, since we're dealing with a constructor. A constructor has no return type. Thus you can't use `std::enable_if` on the return type to select or disable the function.

Similar alternative methods for constructors look less pleasant to use. It is possible to move `std::enable_if` in to one of the argument types. My quick shot at that leads to problems trying to infer template arguments.
```cpp
template<typename T>
MemoryReader(std::enable_if_t<std::is_trivially_copyable<T>::value, T>& object) {
	MemoryReader(&object, sizeof(object));
}
```

> note: candidate template ignored: couldn't infer template argument 'T'
                MemoryReader(std::enable_if_t<std::is_trivially_copyable...

Maybe a static constructor method would work better.

**Comment by Brett208** [comment]
@DanRStevens, I was thinking of templates at first, but had no idea if they were even usable on a constructor. Makes sense that you cannot now that you point that out.

Earlier today, I was just thinking this might work as multiple constructors?

```
std::vector<int> buffer1 { 1, 2, 3, 4, 5 };
Stream::MemoryReader(buffer1);

std::array<int> buffer2 { 1, 2, 3, 4, 5 };
Stream::MemoryReader(buffer2);

std::string buffer3 { '1', '2', '3', '4', '5' };
Stream::MemoryReader(buffer3); 
```

The problem is I don't know how to get the size of the object type or to check if it is trivially_copyable without using a template.

```
MemoryReader(const std::vector& buffer) : streamBuffer(static_cast<const char* const>(buffer.data()), streamSize(buffer.size() * ??????), position(0) { }
```

Brett

**Comment by DanRStevens** [comment]
You can use templated constructors. It's just that constructors and destructors don't have return values. Hence you can't use `std::enable_if` on the return value to conditionally enable/disable them based on type.

To conditionally enable/disable a function, you generally use `std::enable_if` on the return type, since the syntax looks cleanest there. You can also use it on function arguments. You do however need to allow the compiler to infer template types before it can test them though, so that creates complications when using `std::enable_if` on function arguments. In particular, arguments are part of the function signature, while the return type is not. Put another way, a function can be overloaded based on the arguments, but not on the return type. You need those argument types to be set before `std::enable_if` can make them disappear and produce an invalid function definition.

Side note: Vectors and arrays are both templated types, hence to accept them in a constructor requires a template specialization of the constructor.

----

If you check the documentation for [`std::vector`](https://en.cppreference.com/w/cpp/container/vector), you'll notice the "Member types" section. The standard containers often declare aliases for their template types in this section, which gives an easy way to access the type parameter at a later point in the code. In particular, you want the `value_type` member. This has traditionally been a `typedef` for the container type `T`, though newer compilers could potentially use `using` to create this alias now.
```cpp
MemoryReader(const std::vector& buffer) : 
    streamBuffer(static_cast<const char* const>(buffer.data())), 
    streamSize(buffer.size() * sizeof(buffer::value_type)), 
    position(0) { }
```

----

I like your proposal to support all of `std::vector`, `std::array`, and `std::string`.

----

If the constructor can not be suitably parameterized, we could potentially create additional static constructor functions, or perhaps the term is factory functions:
```cpp
MemoryReader createFromVector(std::vector buffer);
MemoryReader createFromArray(std::array buffer);
MemoryReader createFromString(std::string buffer);
```
Of course we could overload the function name if we wanted. Additionally, the `std::enable_if` trick should work here, since this function has a return type.

**Comment by Brett208** [comment]
I think the benefit of constructor overloads is it is more intuitive in this case. However, if we cannot check for is_trivially_copyable on a constructor overload, it allows the user to do unintentional bad things on accident.

I think my preference would be to use the static factory functions (not sure on term either) since it would be more correct. 

What about:

``` C++
Streams::MemoryReader CreateFromContainer(std::vector buffer);
Streams::MemoryReader CreateFromContainer(std::array buffer);
Streams::MemoryReader CreateFromContainer(std::string buffer);
```

The only problem here is I don't know if people intuitively think of a std::string as a container?

Thanks,
Brett

**Comment by DanRStevens** [comment]
This looks like something we've long since implemented in the library. I'm going to close this. If I've missed something, it can be re-opened.
