### ISSUE TITLE
Move const variable declarations into class

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#197]
We have the following const variables inside volFile. Do we want to leave these outside the VolFile class definition, or move them in as private variables? If we want to leave them in the .cpp file and not part of the class, should we mark them static. I think this would make them be only contained in the local translation unit.

```
// Volume section header tags
static const std::array<char, 4> TagVOL_{ 'V', 'O', 'L', ' ' }; // Volume file tag
static const std::array<char, 4> TagVOLH{ 'v', 'o', 'l', 'h' }; // Header tag
static const std::array<char, 4> TagVOLS{ 'v', 'o', 'l', 's' }; // Filename table tag
static const std::array<char, 4> TagVOLI{ 'v', 'o', 'l', 'i' }; // Index table tag
static const std::array<char, 4> TagVBLK{ 'V', 'B', 'L', 'K' }; // Packed file tag
```

**Comment by Brett208** [comment]
Edited description

**Comment by DanRStevens** [comment]
This is good attention to detail.

I had to actually check what putting `static` on a global variable would do. You're right, it makes the name only accessible to the current translation unit. That would prevent someone from writing an `extern` declaration in another translation unit and gaining access to it. Since the variable is a private implementation detail, this would make sense. Without `static`, or an anonymous namespace, it is merely hidden by default, rather than not accessible.

----

As for leaving the constants in the .cpp file, or moving them into the .h file as private members, I think I'm leaning towards leaving them in the .cpp file. They are an implementation detail for loading/saving of VOL data, which is a detail that only matters to the functions that implement that, rather than a class wide concern. In particular, if those details change, you only need to recompile that one translation unit, and not everything that imports the header file.

I admit though, that feels like a bit of a weak argument. Why should any `static const` data be made private members of a class in a header file then? It feels like there should be some good reason for it, but I can't think of any. At least nothing short of using that constant in the header file itself, such as in an inline method, as a default function parameter value, or as a default initialized value.

**Comment by Brett208** [comment]
Yeah, I had attempted to read the page you linked earlier but the material was really dense. In light of these being const variables, it sounds like they are only visible in the local translation unit, so we do not have to mark them as static as well. (Although in C, we would have to mark them as static). 

We can just close this issue I suppose.

**Comment by DanRStevens** [comment]
Probably right, I don't see anything to do here currently. We can always re-open if some other consideration comes up.
