### ISSUE TITLE
Allow controls for how FileStreamWriter manipulates files

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#22]
Currently FileStreamWriter implies overwriting an existing file if it exists and assumes file being written is in binary format. Instead, I would like to add a BitField that allows specifying how a file being written to is manipulated.

Maybe:
```
enum class FileWriteFlag
{
    overwrite = 0b0000'0001, // Allows overwriting existing file
    append = 0b0000'0010, // Allows appending information to existing file
    binary = 0b0000'0100 // Specifies binary file instead of text file
}
```
Default assumption of FileStreamWriter will be to abort writing if file exists and to write in text format. I think we will mostly be using binary, but the fstream class assumes text as default (I think) so this will keep syntax close to standard library.

**Comment by DanRStevens** [comment]
Good idea to add such a parameter. Could probably specify a default parameter value. Unless of course you want the programmer to really think about what they want, and force them to be explicit.

Might be worth checking documentation for other systems, such as the Windows API [CreateFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx), to see what other flags they offer. There might be a more sensible set of flags than whatever the C API decided upon 40+ years ago. In particular, the `dwCreationDisposition` parameter is worth thinking about.

You make a very good point about being compatible with existing practice concerning text mode. It is best to avoid surprises. Though I guess that's one reason why I've traditionally hated text mode. It makes often surprising conversions to data. I've long felt the text mode default was a mistake of older APIs. Text mode corrupts binary data, but binary mode doesn't corrupt text data. Plus, it feels like the conversion is being done in the wrong place by making it a part of the file API like that, rather than a higher level layer. Interestingly, the Windows API has no concept of a text file.

**Comment by DanRStevens** [comment]
I was just taking a look back at this. We've had PR #25 open for about 3 months now. Perhaps it's time to revisit. Hopefully we have a better sense of what we need here now.

In terms of support, I'd like to be able to do the following for opening a FileStreamWriter:
Open a file whether it existed before or needs to be created new (default)
Fail if the file already exists
Fail if the file doesn't exist (maybe?)
Truncate existing data to length 0
Do not truncate existing data
Start writing at either the beginning (default) or at the end (append)

I would like to avoid support for any text mode line ending conversions. I think that is better solved at a higher level. In particular, if you use specific methods to read string data (which might convert line endings), you could do so safely in a mixed mode file that contains both binary and text data. That is, line ending conversion is a property of the data itself, not of the file.

In terms of bit flags to support those operations, perhaps:
OpenExisting
OpenNew
Truncate
Append

**Comment by Brett208** [comment]
I would recommend against coupling the default settings of starting to write from the beginning of an existing file with not deleting the existing contents of the file. I think this behavior can cause obscure bugs when the user intends to overwrite the file. It will work if the contents are the same or longer, but if the new content is smaller than the file's current size it will fail when reading back in later in an application. I've done this before, especially before I knew to watch for it.

From my experience, I almost always intend to overwrite an existing file as opposed to writing from the beginning of the file without deleting the existing contents. I think the better default when writing would be to truncate an existing file.

The problem with not truncating by default, means the flag would need to be named differently. I think Truncate is a fairly common word in programming. What about using the word Extend or Continue as the opposite of Truncate? So the default behavior could be Extend = false.

---

It is worth reviewing the current branch on the subject for how to construct an enum of the flags and the limitations of ifstream's current flags. In particular, I found wrapping a non scoped enum in a namespace the easiest to work with. A scoped enum requires casting when performing bitwise operations. A non-scoped enum will polute the global namespace with all the flags. Wrapping the non-scoped enum in the namespace keeps the enum members out of the global namespace and eases the need for casts when performing the bitwise operations. I may have missed something with the scoped enum that could allow for easier use though as I'm not really experienced with them.

I don't have an opinion on the binary/text flags. I had planned to add them simply to mirror the std library, but I do not have experience using them. If you feel they are detrimental, then we can leave them out for now. They can always be added later if we change our mind.

Thanks,
-Brett

**Comment by DanRStevens** [comment]
Good point about truncating. This is a stream library after all. For a random access model, the default is likely to open an existing file, such as a database, where it might both read and update, and so you wouldn't want to truncate. For a stream though, you would either perform only read operations, or only write operations. For a write stream, it makes the most sense to truncate and write from the beginning (default), or append to the end of existing data.

We don't need the default flags to be 0. Let's not go too far out of our way to require that. Either way, we end up setting a default value for the open parameter. Now that I think about it, the 0 default is more of an issue for compatibility, if we add new flags in future releases. That would be important for binary compatibility with dynamic linking, and to a lesser extent, source level compatibility with non-default parameter sets.

The details of the enum I'm willing to get a little bit wrong, since we could potentially swap between a `namespace enum` and an `enum class` and maintain source level compatibility. I believe an `enum class` could overload `operator |()` to implement cast free bit combinations. It may be easier to start with a `namespace enum` though.

**Comment by Brett208** [comment]
I hadn't thought about operator overloads on a scoped enum. If that is possible, it might make for an interesting solution. I tend to tread carefully when combining creativity and creating operator overloads, although maybe this would be a natural use case.

If other programmers use streams for random write access more often than overwriting a file, maybe the original defaults are better.

**Comment by DanRStevens** [comment]
For reference, I came across this article on [using enum classes as type safe bitmasks](http://blog.bitwigglers.org/using-enum-classes-as-type-safe-bitmasks/).

I don't think random updates are common with streams. That's more for random access read/write files. We should probably design the stream interface for the default case of creating a new initially empty file.

**Comment by Brett208** [comment]
That is a nice article and easy to understand. Thank you for posting.

So, you would be able to conduct bitwise operations between different scoped enums as long as both enum sets were marked to allow bitwise operations. It might be nice to restrict that, but also not that big of a deal.

**Comment by DanRStevens** [comment]
Err, between different scoped enums? Generally you'd only want it within a single scoped enum, which is what the article describes.

The examples with mixed enums were examples of bad code which the compiler wouldn't fail on for regular enums, but would flag as an error for scoped enums. Hence the case for using scoped enums. By default, or even with the proposed operator overloads, mixing of different scoped enums is not allowed. You'd have to go out of your way with explicit operator overloads taking mixed parameters to allow that. Which of course is a generally bad idea.

Or did I misunderstand what you were saying?

**Comment by DanRStevens** [comment]
I got the opposite impression. In particular, the implementation given at the end is:
```
template<typename Enum>  
typename std::enable_if<EnableBitMaskOperators<Enum>::enable, Enum>::type  
operator |(Enum lhs, Enum rhs)  
{
    using underlying = typename std::underlying_type<Enum>::type;
    return static_cast<Enum> (
        static_cast<underlying>(lhs) |
        static_cast<underlying>(rhs)
    );
}
```
You'll notice the function signature uses `operator |(Enum lhs, Enum rhs)`. In particular, the left hand side, and the right hand side both use the same type `Enum` (the template parameter). Hence the operator overload only exists when the enum types match.

**Comment by DanRStevens** [comment]
For reference: [ofstream](https://en.cppreference.com/w/cpp/io/basic_ofstream)

Available open modes are:
> `app`	seek to the end of stream before each write
> `binary`	open in binary mode
> `in`	open for reading
> `out`	open for writing
> `trunc`	discard the contents of the stream when opening
> `ate`	seek to the end of stream immediately after open

There does not appear to be any flags to test for the presence or absence of a file before opening it.

We can clear the contents of a file by truncating to length 0 with `trunc`. We can automatically seek to the end of the file with `ate`.

We probably have no use for `app`, which ensures every write goes to the end of the file, even if you seek elsewhere first. That would be more useful for random reading + writing, which is not supported by a unidirectional stream.

We have no use for text files, so `binary` will be permanently set. Similarly, for the output streams, `out` will be permanently set, while `in` will be permanently cleared.

----

I suppose we can pre-check the existence or absence of the file before opening to implement the other semantics. That would be subject to race conditions, so not entirely secure. It would be fine to simply document that though. For most purposes, people simply won't care.

Properly handling pre-checks for file existence or absence is likely to be platform specific. If we decide to someday support that, we could do so with platform specific code, contained in `#ifdef` blocks.

----

As the internal file object is contained by `FileWriter`, we are using a constructor initializer list to initialize it. As such, it will have already initialized and opened a file before the FileWriter constructor runs. Hence trying to check for the existence/absence of a file in the constructor will be too late.

Inside the initializer list, when feeding flags to the internal file object, perhaps we are able to call a static method to translate the flags, which can also pre-check the existence/absence of the file.

**Comment by DanRStevens** [comment]
In case we revisit this for platform specific solutions to the race condition associated with file existence pre-checks, I thought I'd leave a few links.

[CreateFileW](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilew) - Windows, see `dwCreationDisposition` values 
[open](https://linux.die.net/man/3/open) - Linux, see `O_CREAT` and `O_EXCL`

For converting from a Windows API `HANDLE` to a `FILE*`:
[Is there a Windows equivalent to fdopen for HANDLEs?](https://stackoverflow.com/questions/7369445/is-there-a-windows-equivalent-to-fdopen-for-handles)
