### ISSUE TITLE
Make Archives codebase cross-platform compatible

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#30]
Currently Archives codebase contains windows specific implementation details and relies on Windows.h.

Windows specific dependencies are mostly related to file handles and associated code.

**Comment by Brett208** [comment]
My first step is representing a CLM file as a struct called ClmData. Hopefully this will allow representing a CLM File without relying on opening a handle to an existing file. This will eliminate the Windows specific file handle currently in use with calls to the OP2Utility MemoryStream code. 

See the gist here for proposed structure https://gist.github.com/Brett208/707db720e4d9f3dc82fe8893e1f54a0b.

I'll try to make a couple of smaller commits to start, but there will have to be a fairly large codebase change when the actual handle to the file is removed.

Fixing the vol files to match this pattern will be a separate effort assuming that we get CLM files to work in this manner.

@DanRStevens looking for your feedback on the proposed struct before beginning, including naming choices, types, and if the overall idea seems like a good idea.

**Comment by DanRStevens** [comment]
Hmm, I notice the ClmData struct has a fileData member to point to the contents. The issue is, the CLM file is quite large (251MB), and such a member implies a full memory load. Typically, only a single internal stream is opened at a time, and even that is read in chunks rather than doing a full memory load.

Another odd point is the fileVersion string from ClmHeader. A `std::string` is usually a small struct with a pointer to the string data. The actual file format though is just the raw byte array without the hidden fields. The ClmHeader struct won't accurate represent the on-disk format.

Similarly the fileName field of the IndexEntry struct will also differ between memory and disk.

I'm not sure there is a clean way to do this and get consistent representation between memory and disk while also using `std::string` in this manner.

If it helps, I noticed the OP2Editor project has split ClmReader and ClmWriter classes. If the COM stuff is discarded, what remains may provide a reasonable base to work from.

**Comment by Brett208** [comment]
I was planning on having the entire clmFile in memory before either saving a copy of it or extracting a file from it. This made sense to me because once it is all loaded it is trivial to complete tasks against it, such as deleting a file in the middle or adding a file. 

I hadn't thought about the memory footprint. I'm not sure that using 250mb of memory is a problem though, especially without testing. However, I would be okay designing to only load the CLM Header and Index Entries into memory. I suspect this is mostly what is happening in the current setup? I'll try to review the OP2Editor code in the near future.

If this is how we want to proceed, I would like to consider closing the handle between function calls. What I mean is, when opening a CLM file, the header is read from the file and then the handle closed until the next call to say extract a file when it would be reopened. I think this would make it easier to create a default header in memory when writing a new CLM file.

Concerning the use of std::string, I prefer using it here for the typical reasons of protecting against the vulnerabilities of a c-style array like setting values outside the bounds of the container. It also guarantees the null terminator is appended, which doesn't exist on one of the MapFile strings when loading from disk. I have not had problems when representing TileGroup::name and TilesetSource::tilesetFilename as std::strings after loading from disk and then saving to disk. When saving a std::string to disk as long as only the used size of the container is iterated over, it doesn't really matter if the underlying container is allocated larger than needed. Maybe I'm missing what your concern is though?

Since both fileVersion and IndexEntry::fileName are both fixed in size, I would be okay trying to use a std::array<char, X> to represent them. This would allow for better bounds checking then a C style array.

If we want to store the data as an array, then we could create a GetVersionInfo and GetFileName function that returns a std::string containing a copy of the characters.

Glad we are hashing this out before I started coded. Let me know what you think.

Thanks,
Brett

**Comment by DanRStevens** [comment]
Back when OP2 was relased, computers had nowhere near 250MB of RAM. Maybe more like 32MB, so a full memory load would have been impossible. The program would have crashed due to insufficient memory.

You could do a full memory load these days, though there will be noticeable startup delay if it loads 250MB at once. Stream processing can hide that, and make the program appear more responsive. Plus, if you don't need it all in memory at once, stream processing is a good paradigm to use.

I would not recommend closing the file handle in a stream processing setup. Quite a few errors can happen when opening the file, so keeping it open sidesteps a few issues. Think what happens if a file gets renamed or deleted after the index was first processed. Keeping it open means the OS will still have access to the data. A delete won't take full effect until the last file handle is closed. Plus, there are few resources required to open a file.

The above advice applies to the CLM and VOL files. During packing you'll have to open many more files, and there is a limit to how many can be opened at once. In old code I did open all the WAV files first, and checked the headers before attempting to pack. In hindsight, I think they should have been opened one at a time during packing, and errors handle with an exception.

For the TileGroup comment, did you read a struct directly from disk that contained a 'std::string', or did you load the string separately on its own, after sizing it? The first way may be subject to vagaries of standard library implementation details, and the size of the string. I would not recommend it. One of the benefits of defining and using some of these structs is that it allows for easy and quick loading and saving of data in a single call to process the entire struct. Though it sounds like you may have used the second way, which should work, just it requires more code.

The 'std::array<char, X>` should work just fine. That probably is better than a raw array.

I'm fine with a GetFileName method. We probably don't need a GetVersionInfo method, since we really only support one version. We could just raise an exception during load if it doesn't match what we expect.

**Comment by Brett208** [comment]
Okay, here is what I have planned now:

1. Replace char[] with std::array<char, X> where applicable in CLM Header if the size of the char array is a fixed length.
1. When loading a CLM file from memory, replace the Windows specific file handle with FileStreamReader. Leave FileStreamReader open for the duration of the class' existence.
1. Only store the header information in memory and not the actual packed files.
1. When Creating a new CLM file, use FileStreamReader to access each file on disk sequentially, releasing it before the next file is processed. 
1. Check each file for packing to ensure it is written in the same format as the first audio format in the archive. Abort otherwise.

I'm not sure that our current StreamReader/Writer classes are robust enough to handle this without some modification.

As for loading data into stream: Here is how I'm storing the string for the MapReader. When reviewing it, I realized that there is a possible resource leak if StreamReader throws an error as tileGroupName will not be deleted. Also, tileGroupName should be named a generic stream in this function as it is used for loading any stream from file. I'll clean both those issues up shortly.

```
// String must be stored in file as string length followed by char[].
std::string MapReader::ReadString()
{
	size_t stringLength;
	streamReader->Read((char*)&stringLength, sizeof(stringLength));

	if (stringLength == 0) {
		return std::string();
	}

	char* tileGroupName = new char[stringLength];
	streamReader->Read(tileGroupName, stringLength);
	std::string s(tileGroupName, stringLength);

	delete tileGroupName;

	return s;
}
```

**Comment by DanRStevens** [comment]
You can eliminate the `new`/`delete` calls by using [reserve](http://en.cppreference.com/w/cpp/string/basic_string/reserve) on the `std::string` object. See StackOverflow for an example of [Pre-allocating memory for a std::string](https://stackoverflow.com/questions/3303527/how-to-pre-allocate-memory-for-a-stdstring-object), with the example being reading from a file.

For point 4, it's ok to construct a new FileStreamReader for each opened file. In fact, I would recommend it. This would be cleaner than adding methods to the FileStreamReader class to support closing or opening a new file after construction.

For point 5, it would be reasonable to have a default assumed audio format. I believe Outpost 2 only supports a single audio format for CLM files. The CLM file format could potentially support other audio formats, but I don't think OP2 would be able to use it. As such, reworking the format check is completely within reason.

The essential part for point 5, is all audio files must be the same format (or converted to the same format), as the WaveFormatEx is shared for all component files. If this can't be met, an exception should be raised, and the operation aborted with an error.

A potentially nice to have feature for point 5, is if the audio format does not match what OP2 expects, a warning could be issued to the user, and the operation could be allowed to continue. This is not essential though. Also, how the audio format is selected could be changed. I tried to auto select a format based on the first processed WAV file. Perhaps this could be set with a command line option (possibly implemented in a future version), where the default is the format expected by OP2. If any processed audio files don't match this format, an error could be raised. This might allow simplification of the packing code. It might also better support audio format conversions in a future version.

**Comment by Brett208** [comment]
In regards to removing the Windows header from the VolFile class, we will have to deal with the MemoryMappedFile parent class. I'm not really sure what to do with it. I noticed it calls the Windows specific function `CreateFileMapping`. 

Maybe the first question is what is a MemoryMappedFile and why are we using one?

**Comment by DanRStevens** [comment]
Yes, that will be the most challenging part.

Memory mapped I/O is when part of the address space of the process is reserved and has a file's contents mapped into it. It can be the full file, or a partial window into it. Conceptually, to the program, it looks like having a buffer at that address with the contents of the disk file read into it. The difference, is the file might not actually have been pre-loaded into the buffer. Instead, it uses the virtual memory system. If a memory page hasn't been loaded, it causes a page fault, and suspends the thread while the OS loads the contents from disk. Writes to that memory buffer will be flushed to disk, much like how virtual memory can be paged out to disk when a system is low on RAM. The benefits is lower latency, since it doesn't need to read the whole file at once. For Windows, it was even found to be faster, where even code that reads sequentially from disk can perform faster with memory mapped I/O than going through the filesystem API.

There are some Linux API methods for memory mapped I/O, though that sort of thing tends to be somewhat system specific. We won't find the equivalent of fstream to help us out. It would have to be #defined Windows/Linux specific code to keep using memory mapped I/O for both systems.

As for why it's being used, simply because that's how the game did it, and I was closely following the game's code. I'd recommend ripping that stuff out and converting to regular file system API code if we want to make that stuff cross platform. Unfortunately that means more extensive changes to the structure of the code for this part.

**Comment by Brett208** [comment]
Okay, I was thinking of ripping out the MemoryMappedFile as well, so we are on the same page. I'll plan to continue refactoring the volume write code first to get more comfortable with the volume file format before working on the volume read code.

I'm thinking we can rewrite `struct CreateVolumeInfo` into `VolumeInfo` and use it in both the read and write process. I think this can be accomplished by removing the specifics about files to be packed and passing them seperately. 

Thanks,
Brett

**Comment by DanRStevens** [comment]
Yes, the volume info can stand to have a few fields trimmed, or possibly turned into derived values (functions returning a calculated value).

In particular, I don't think the `fileNameLength` array is really used anymore, since those lengths can be derived from the `std::string` objects now. There is a write that still uses it, to write the string and it's null terminator, though it can calculate that as `string.size() + 1`. There is also an offset calculation that uses it, but mostly only as a temporary.

The padded lengths could also become derived values.
