### ISSUE TITLE
Rewrite ArchivePacker::CreateArchive to be exception based instead of returning bool on success

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#44]
Will involve refactoring VolFile::CreateArchive and ClmFile::CreateArchive. 

rewrite:
```virtual bool CreateArchive(std::string volumeFileName, std::vector<std::string> filesToPack) = 0;```

to read:
```virtual void CreateArchive(const std::string& volumeFileName, std::vector<std::string> filesToPack) = 0;```

**Comment by DanRStevens** [comment]
I agree with the return code versus exception change.


I noticed the `volumeFileName` parameter changed as well. I had to think about this. It probably makes sense to change it, with similar reasons applying to the second parameter as well.


We should perhaps figure out some guidelines for when input strings, and other objects, should be passed by const lvalue-reference, by lvalue-reference, by rvalue-reference, pointers, or by value. My initial take on this is:

The const lvalue-reference (&) is appropriate when the string is owned somewhere else, and access is borrowed. You should not store a caller owned lvalue-reference somewhere that might outlive the input value (otherwise you end up with a dangling reference). Typically the caller continues to own the object, and is responsible for the lifetime. It's possible to transfer ownership, though this is usually unexpected, and would need to be a documented part of an API. A const lvalue-reference can accept a temporary value generated by an expression. No copy is created.

An lvalue-reference (non-const) is suitable for out parameters, where the caller expects the value to be updated. A non-const lvalue-reference can't accept a temporary value generated by an expression, and so must be passed a named variable. This means you can not pass a constant literal expression, such as a hardcoded number or string. Ownership is by convention, where the caller may still own the object or transfer ownership, depending on the API design, though the usual expectation is the caller owns the object. No copy is created.

The rvalue-reference (&&) is only appropriate when you're assuming ownership of an object. It may invalidate the original value from the caller when it assumes ownership. Think of this like passing a unique_ptr, where once passed in, the caller no longer has access to it because it was invalidated. An rvalue-reference can accept temporary values created by expressions. It can use the move constructor as opposed to the copy constructor for better performance, allowing internal resources such as buffers to be transferred, without being reallocated and copied. The move may copy buffer pointers, rather than full buffers.

Pointers (and const pointers) can be used in place of lvalue-references (and const lvalue-references) if support is needed for `nullptr`. For cases where `nullptr` is not expected nor desired, prefer the corresponding lvalue-reference instead.

The by value approach is suitable for any other type of input. It may be used in the above cases as well, though with lower efficiency due to needless copying. In particular, since it makes a copy, it doesn't concern itself with the lifetime of the original, and doesn't affect the lifetime of the original. It can accept temporary expressions. It may cause performance issues if large objects are copied frequently.

**Comment by Brett208** [comment]
I'll plan to tackle this next.
