### ISSUE TITLE
Represent VolFile tags as a standardized data member

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#57]
Consider making a separate struct to represent a VolFile tag.

```
struct volTag {
    std::array<char, 4> tag;

    // Length must be a multiple of 4 bytes.
    uint32_t length;
}
```

**Comment by DanRStevens** [comment]
I could go for that, especially if there is an easy way to initialize them with string constants, such as "VOL ", "volh", "vols", "voli", and "VBLK". A constructor might be hardcoded to accept a `char[5]` to account for the null terminator.

----

A bit off-topic but, Is there a reason you put comments before the data declaration lines, as opposed to on the end? Does it affect IDE helper info? I ask because I'm used to seeing structs packed might tighter in the source code, with comments at the end of what are usually fairly short lines.

More unrelated, I also tended to pack interface methods closer together without blank lines, though I can see reason for expanding that as interface methods usually get more documentation.

**Comment by Brett208** [comment]
This issue was addressed a while ago an just not closed out.
