### ISSUE TITLE
Consider using `std::size_t` instead of `size_t`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#62]
There is a subtle [difference between `size_t` and `std::size_t`](https://stackoverflow.com/questions/5813700/difference-between-size-t-and-stdsize-t).

Standard C types were imported into C++ and added to the `std` namespace. The standard guarantees the global C type (if it is defined) will match the corresponding `std` type. I've noticed the standard doesn't seem to require the types be available by default, but allows for `#include` of any standard library to define them.

As this is a C++ project, it might be better if we use `std::size_t`. We might also want to pay attention to any required header files. On cppreference.com, the [`size_t`](https://en.cppreference.com/w/cpp/types/size_t) page lists a few headers that define the type. A common one I see listed for the type is `<cstddef>`.

I tried running the new version of Clang on the project, and it barfed all over the `size_t` types, saying they were undefined.

----

A related but slightly different matter, is I think we are using `size_t` more often than we should. For-loop variables can and probably should be declared with auto when possible, at least for the new style for-loops. We also have `size_t` in a few places where a fixed size type would be more appropriate.

I recommend we update the code to reduce the number of explicit uses of `size_t`, and change the type in a few instances where another type would be more suitable.

I also recommend we use `std::size_t` for the instances that remain.

**Comment by Brett208** [comment]
MSVC seems quite happy with the current size_t code, but of course we need it to work on the Linux compiler as well. @DanRStevens, is the primary compiler we want to support for Linux builds Clang?

In the future, I'll use the cheat sheet below and make sure at least one of these headers is defined in a file when using size_t. If none of the headers are present, I'll use cstddef by default. (https://en.cppreference.com/w/cpp/types/size_t):
 - header <cstddef>
 - header <cstdio>  
 - header <cstdlib>  
 - header <cstring>  
 - header <ctime>  
 - header <cwchar>

I'll start writing it as std::size_t. 

I've typically steered away from using the auto keyword as I prefer seeing the actual type when reading code instead of trying to determine it in context (hovering and using the tooltip also works in Visual Studio). This seems to be a bit against standard practice so I'm game trying to use auto more, especially in range based loops. 

I'm guessing that if the auto keyword resolves to size_t, one of the headers containing size_t must be present to satisfy the Clang compiler? I'm guessing since vector and array use size_t for their length, they also define size_t?

Thanks for pointing this out,
Brett

**Comment by DanRStevens** [comment]
Edited your header list to use code blocks. Things in angle brackets don't display otherwise.

I used to like knowing the explicit type as well, though I've come to appreciate auto. Especially when the actual type is very long to type, or when you might change parameter types and don't want to have to change all the dependent types.

We should really try to use the new range based loops when possible now.

Correct about headers having already included `size_t` if `auto` resolves to it. In particular, `auto` resolves to the type of the expression it's being used with. For that expression to resolve to that type, that type must have been declared somewhere already.

In regards to `vector` and `array`, there is good reason to use auto:

> When indexing C++ containers, such as std::string, std::vector, etc, the appropriate type is the member typedef size_type provided by such containers. It is usually defined as a synonym for std::size_t.

As for the Linux compiler, the default is g++. I've been noticing a bit of a trend towards Clang though. I've found Clang seems to be the strictest with compiler checks. If code satisfies Clang, there's a pretty good chance it will compile elsewhere. It also conveniently uses the same command line options as g++, so it's a pretty easy drop in replacement.
