### ISSUE TITLE
Allow reading from a slice of a file

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#69]
Allow for passing only a portion of an existing file for reading to another part of the application.

This is high priority as the codebase is currently broken without it.

**Comment by Brett208** [comment]
A first draft of a FileSliceReader is below. It currently is a child of FileStreamReader. It may be more beneficial to not make it a child of FileStreamReader though. It is written a bit in pseudo-code.

https://gist.github.com/Brett208/14192de33ed2d5bf5f3580a81ad39493

Open to other suggestions, although I'd like to get the code base working soon.

**Comment by DanRStevens** [comment]
You're probably right about not making it derived from FileStreamReader. All of the virtual methods have to be overridden, so it doesn't share much in terms of implementation details. Probably better to make it an independent class that derives from SeekableStreamReader.

Technically, it should be possible to take a slice of a StreamReader class too, but lets try to limit the scope for now.

Line 26 looks like a bug. I'd recommend storing a starting position and a length, rather than a starting position and an end offset. I think it might be a little more intuitive that way. Input parameters will be in the range 0..length, output parameters to the delegated internal stream will be in the range startOffset..(startOffset + length). Parameter checking is likely to be done on the first range, rather than the second range.

Line 20 looks like a bug. The `Length()` method is on the current object, not the internal stream object. I'm glad that you thought to check this though.

----

The exact type of the internal stream is arbitrary. You could take a SeekableStreamReader as a parameter, rather than a filename, allowing slicing of any seekable stream. However, you need to be mindful of how interactions between the original stream and the sliced stream affect the file pointer. For now, it may be simpler to limit scope, and pass a filename to open a new file. A separate internal ifstream object will ensure separate seek pointers. The downside being this is highly specific to slicing of file streams. That's fine for now, and can allow master to be fixed.

**Comment by DanRStevens** [comment]
Correct about the existing MemoryStreamReader being able to just view a different subset of an existing buffer. You wouldn't need to implement a new class to support slicing there, just update the pointer and size in a new object. That also nicely handles having separate stream positions.

I think slicing an existing stream is exactly where most of the value of slicing comes from. Perhaps I need to put some of my thoughts on slicing down in writing to help crystallize the concept.

**Comment by Brett208** [comment]
Second draft of FileSliceReader is now contained in branch #67, Fix Bugs When Reading and extracting from volume files.

FileSliceReader tests successfully by allowing a packed file to be imaged by OP2MapImager without being extracted from the volume first.

Looking forward to seeing your thoughts on the matter if we move that direction.

Thanks,
Brett
