### ISSUE TITLE
Allow for automatic writing from an existing stream

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#84]
A common use case is reading from one stream and then writing that data immediately to another stream. We could standardize the process by including support in the stream library.

One solution would be to attach to following functions to StreamWriter. The first function could be omitted, which would allow adding only StreamReader as an include instead of SeekableStreamReader.

```
// Writes from the current position of the passed stream until the end of the stream.
// Takes an optional bufferSize to specify how large of chunks to read each pass.
void WriteFromStream(SeekableStreamReader& seekableStreamReader, size_t bufferSize =  0x00020000)
{
    WriteFromStream(seekableStreamReader, seekableStreamReader.Length() - seekableStreamReader.Position(), bufferSize);
}

// Writes from the current position of the passed stream through the specified writeLength.
// Takes an optional bufferSize to specify how large of chunks to read each pass.
void WriteFromStream(StreamReader& streamReader, uint64_t writeLength, size_t bufferSize = 0x00020000);
```

Another option might be to create a separate header that includes the functions standalone. It would require adding the StreamWriter as an input to the functions.

These 2 functions would both be used in ClmFile and VolFile, so I'm guessing their application would apply to other applications as well.

I just chose the default bufferSize because it is used in other parts of Archives and am not sure if a different default might be better.

**Comment by DanRStevens** [comment]
I think we should support this in the Stream library. I definitely think such functionality will be generally re-usable.

The method, as given, does seem like a generic standalone method, so a separate standalone .cpp file makes sense. We could modify it and attach it to a specific stream class as well, with StreamWriter being the most obvious. It feels slightly weird to attach it to StreamWriter, but at the same time, I suspect that might be most convenient.

I'm wondering if "Consume" might be a good name for the method. That would sound natural in the context of a StreamWriter class. An alternative might be "Pipe", though more for the context of a StreamReader class.

----

If we get around to writing test code, we could do some actual speed tests and perhaps choose a buffer size that hits a sweet spot for performance versus memory use. For now though, I'm happy to just stick with whatever value was being used previously.

**Comment by Brett208** [comment]
If attached to StreamWriter, it would read as streamWriter.ConsumeStream(streamReader, 100);

I like how ConsumeStream sounds better than WriteFromStream. I think the only downside is that this gives the connotation that the entire stream is consumed, where in reality it could only be a portion of the stream.

I haven't used a library that uses Pipe before, so this one doesn't seem as appealing to me. 

So probably ConsumeStream.

---

I wonder if the optimum buffer size will be affected if the code is compiled for x86 vs x64. Maybe have a preprocessor directive to switch based on compilation. The optimum value may also be a function of the size of the overall read. A small table could be constructed that picks a value based on the length of the overall read. But like you said, lets just get this in the codebase for now.

-Brett

**Comment by DanRStevens** [comment]
If we complete a nice design for slicing, and get that into the library, it would be quite natural to only support consuming entire streams directly, and just use slices to limit consuming to part of a stream.

Also, if we name it just "Consume", it would be more natural to potentially provide overloads for other input sources in the future. Maybe something representing an OS level stream that has a different interface than the Stream library.

Or, maybe it can just be another template overload to Write, except that it takes a StreamReader derived class as input. That might actually be the most consistent with existing library usage.

----

There might be some difference between x86 and x64, but I sort of doubt there'd be a large difference. It's the same underlying hardware. What would likely produce a noticeable difference is a regular hard drive versus a solid state drive. Total copy size is also important. I suppose we could pick a buffer size at runtime based on settings, such as the copy size. Testing would reveal the numbers, as well as whether or not it's worth it to make a runtime choice.

----

I think this issue brings up an important limitation about the current streams design. In particular, there seem to be two types of stream consumers, and we've currently only accounted for one. We've handled the case of a stream parser, where the consumer is trying to specifically parse a certain data type. With this sort of code, we don't want to have to error check every read, so an exception raising read is much more convenient.

The other type of stream consumer is one that just copies a stream from one place to another, without caring to interpret the data at all. Such software likely doesn't care to break the stream up in any special way based on the data structure, and so won't know and won't care what the data format is. As such, it can't parse any meaningful length information from the stream data itself. It must rely on overall stream properties to deal with sizing. Such use will likely copy the stream in fixed sized chunks, with a potential partial copy for the last chunk, as the stream size likely won't be an exact multiple of the chunk size. For this kind of looped copy, it makes more sense to check a return value. It would be the same check code each time through the loop, so not too onerous to write.

Perhaps we need two types of Read (and Write) supported by the Stream classes. One checked Read/Write that raises exceptions, and another that just transfers up to the stated size and returns how much was actually transferred. I don't see a reason to change the call signature, so an overload to Read/Write would not be possible, hence we should have a slightly different name for such a function so the library user can choose which one they want:
```
// Returns actual number of bytes transferred
std::size_t ReadPartial(void* buffer, std::size_t size);
```

We would need to give some consideration to what partial transfers means though. If the library user wanted to read up to 512 bytes from a network socket, which has currently only received 128 bytes though is still open, do we return the 128 bytes, or do we wait for more or for the socket to close and indicate end of stream. Similarly, if the socket currently has no bytes available, does that return 0 bytes, or does it block waiting for data. These two might not be the same. It might be we return as much as possible without blocking, and only block if there are 0 bytes to read. Or we might never block. In that case, there would need to be another method to determine when the end of stream has been hit.

Another possibility is to have a blocking and a non-blocking variant. I'm not sure I want to go down that route though. I think I'm inclined towards returning 0 bytes means you've hit the end of the stream, and the interface blocks if you try to read and no bytes are currently available.

Would really like some feedback on this one.

**Comment by DanRStevens** [comment]
@ldicker83, I'd love if you could weigh in on this issue.
@Arklon1, if you've got input, it would also be appreciated.

**Comment by Brett208** [comment]
Even if we have robust support for a stream slice, I would consider still supporting passing a stream and only reading a portion of it. This would prevent the user from having to create an entire new stream slice just to read something into another stream if they don't want to.

If we want to offer both a Read and a ReadPartial option, I think I would lean towards an overload/template of Read for the stream consumption. Otherwise, we would have to add Read, ReadPartial, Consume, and ConsumePartial, which is starting to produce a lot of different member function names.

I'm not sure how to set this up in a template though without some research.

-Brett

**Comment by Brett208** [comment]
To me, I'm thinking the default (or only?) behavior of a slice is NOT affecting the position of the original stream. The term slice would indicate an amount of independence from the original stream. 

If I want the position of the original stream to update with the slice, it would be more intuitive to me to not pass a slice at all but instead pass the stream itself. Then when the work is done, the position will be updated appropriately.

I think the template to read from a stream shouldn't care whether it is passed a slice or a stream. It would just treat them both the same.

I like the idea of being able to return a slice from an existing stream via a function. It might make sense to have 2 versions of the function, one that creates the slice from the current position, and one that allows starting the slice from an arbitrary position in the stream. 

```
SeekableStreamReader StreamReader::Slice(uint64_t position, uint64_t length);
SeekableStreamReader StreamReader::Slice(uint64_t length);
```

-Brett

**Comment by Brett208** [comment]
Goo idea on updating the stream position on slicing.

What do you think about updating the position of the underlying stream if you manually provide an arbitrary start point:

```
SeekableStreamReader SeekableStreamReader::Slice(uint64_t position, uint64_t length);
```

I think in this case it might make sense to not update the stream position? I don't know though and could go either way. It might be best to update the position of the stream in both cases, that way it is consistent behavior across the API?

---

One thing your post made me think about is flexibility in what type of slice is passed. Using

```
StreamReader StreamReader::Slice(uint64_t length);
```

would pass a StreamReader as a slice. This means the consumer would not have access to Seek, SeekRelative, and Length. If I am taking a slice from a SeekableStreamReader, I may want to retain these functions instead of losing them in the slice. I'm not sure what this would look like in the code though. (In theory you might be able to cast the returned StreamReader as a SeekableStreamReader if you knew it came from a SeekableStreamReader source, at least in C# you could, but this wouldn't be an ideal use case in my mind.)

It might be nice to change the return behavior based on the StreamReader class. A SeekableStreamReader should return a slice that is a SeekableStreamReader. The user can reference it as a StreamReader on their own if they don't need the full functionality. A nonSeekableStreamReader would still need to provide a StreamReader for obvious reasons. Not sure if C++ allows overrides that change return behavior though?

-Brett

**Comment by DanRStevens** [comment]
Good point about the seekable slice variant. I don't think it makes sense to update the position there. Seems like a wasted operation. If they are using the seekable version, they are probably providing a slice to a remote part of the stream which the calling code doesn't care to process right now. Much like how the VOL file code cares mostly about the header section, and just passes a restricted stream back for file contents, which the VOL code itself never processes. I imagine other uses would be very similar.

I suppose one aspect I hadn't thought about before, is if you're doing read-ahead to determine how you should process the next bit of data. In that case, you might not want to advance a stream after taking a slice. Like say, checking the first few bytes of a file to read the file marker, and then passing the entire file contents to the appropriate parser. Though there may be other methods to support such use cases, such as a buffered stream, that supports peaking into the buffer.

The consistency of behaviour is an important consideration though. I guess in this case I wouldn't really expect such consistency with seeking, but I suppose other people might have a different opinion. I may be stuck thinking too much about the specifics of what we're doing here, rather than a more general case.

----

Good point about losing access to more advanced stream features. Luckily C++ allows for covariant return types. Which means a SeekableStreamReader could provide an overload with a more specific return type, as could any derived classes. These are all valid `overload`s:
```
StreamReader StreamReader::Slice(uint64_t length);
SeekableStreamReader SeekableStreamReader::Slice(uint64_t length);
FileStreamReader FileStreamReader::Slice(uint64_t length);
```

This would prevent needing to cast from the calling code.

One small point, which isn't a big deal in practice is if you have a SeekableStreamReader stored in a pointer to a StreamReader, you might only see a StreamReader type returned. The underlying type could still be a SeekableStreamReader, so you could cast in that case, however, the correct solution would be to update the original pointer to be stored in a SeekableStreamReader pointer, since that's what you really needed in the first place.

We may want to consider if the [Curiously Recurring Template Pattern (CRTP)](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern) would be useful here. If I remember correctly, it handles this sort of thing well, though it may complicate the class hierarchy and make it less newbie friendly for people who want to derive their own classes.

----

I forgot to reply specifically to this:
> I think the template to read from a stream shouldn't care whether it is passed a slice or a stream. It would just treat them both the same.

If the returned slice is a stream, then it will of course be treated the same. I hadn't really stated this explicitly, though that was my intention that slices also derive from a stream interface.

**Comment by Brett208** [comment]
I think we have a solid enough plan that we should start trying to implement some of this. I'm sure it will change as we move forward and discover unthought of cases.

I'd like to avoid CRTP unless we are unable to make the solution work elegantly without it to reduce complexity as you mentioned.

-Brett

**Comment by DanRStevens** [comment]
Alright. One last consideration, do we want to include `Slice` as part of the main stream interface, or does that become it's own interface, making slice support optional? We complicate the interface by requiring it, and it may not always be appropriate How well can a network socket support slicing? I don't think stream position can be very independent there. We may require additional restrictions, such as not interleaving calls on the child stream with calls on the parent stream.

On the other hand, we complicate the class hierarchy if it becomes optional:
```
Stream
SeekableStream : Stream
SliceableStream : Stream

// Single inheritance: (Hacky, not recommended, choose one)
SeekableSliceableStream : SeekableStream
// Or
SeekableSliceableStream : SliceableStream

// Multiple inheritance: ( still a little hacky, for methods that require both interfaces)
SeekableSliceableStream : SeekableStream, SliceableStream
```

I should comment that although multiple inheritance is generally bad, it's generally permissible for interfaces, such as we have here.

What I don't like about multiple inheritance here, is we've proposed two methods, one of which implies taking a slice with seek support. That makes slicing not entirely orthogonal to seeking. Even if we put the additional method in a new class that inherits from both interfaces, a class could derive from each base interface directly, thereby bypassing the definition required to implement the seekable slicing support.
```
// Implements: Slice(position, length)
SeekableSliceableStream: SeekableStream, SliceableStream

// Required to implement: Slice(position, length)
NormalClass : SeekableSliceableStream

// Not required to implement: Slice(position, length)
SomeOddClass : SeekableStream, SliceableStream
```

Because of the above, I'm thinking we should include Slice right as part of the main Stream interface. Though, we do need some consideration for types of stream that can't implement independent views into a stream, such as a network socket. Once the data is read, it's gone. There is no underlying random access element that could support multiple streams with independent positions.

**Comment by DanRStevens** [comment]
With all the talk of Slicing here, I should add a reference to Issue #72. I think I may have mistook this discussion for that one.

As for the issue of copying one stream to another, this relates to two ways of processing a stream. Using code specifically designed to process a particular type of stream, and expects the data to be there, fully present according to the file format, and using generic code to copy data about or otherwise manipulate streams of data without specific processing of the stream. The first you want checked with exceptions if data is not present or not accessible, such as hitting EOF in the middle of a read. The second way you probably just want to process chunks of data up to some buffer size, and don't care if there's not enough data to fill a buffer.

With that in mind, I think adding the following method would help further support for generic processing:
```
// Returns actual number of bytes transferred
std::size_t ReadPartial(void* buffer, std::size_t size);
```

I think we should start by adding this method into the library.

**Comment by Brett208** [comment]
No problems with multiple inheritance if it is to implement interfaces. Although I think technically StreamReader/Writer are not interfaces because they implement the template function with a body.

I'm in agreement that creating a slice from a stream should be part of the primary interface and not some sort of add-on header.

I'm reviewing some of my previous comments and think maybe I was in error earlier. Since a StreamReader does not have any concept of current position or length, I think it is actually inappropriate to slice it. A SeekableStreamReader is appropriate to slice because you can know where you are at in the stream and how long the stream is overall. This would support the idea that you maybe should not try to slice a network socket stream as discussed. 

ReadPartial sounds good.

I think we are getting too far into discussion without writing code. I'll plan to implement SeekableStreamReader::Slice. It will return a FileSliceReader or a new MemoryStreamReader as appropriate. After the branch is initially written, we can review further and make updates. I'll stay away from working on ReadPartial unless I repost here in case someone else wants to work on it.

-Brett

**Comment by DanRStevens** [comment]
Sounds like a plan.

Good point about not getting too carried away on discussion without writing any code. I have a tendency to be a bit too ivory tower at times. I blame university for that! :grinning: 

I'll tackle the `ReadPartial` stuff.

**Comment by Brett208** [comment]
I would prefer you to take the rest of this issue on. You seem to have specific requirements on how you would like to see it accomplished and it will be easier not going back and forth with changes this way.

-Brett
