### ISSUE TITLE
Extracting from LZH compressed volumes is currently broken

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#85]
It still assumes the file is memory mapped. 

```
void VolFile::ExtractFileLzh(std::size_t fileIndex, const std::string& pathOut)
{
	try
	{
		char* offset = (char*)m_IndexEntries[fileIndex].dataBlockOffset;
		int length = *(int*)(offset + 4) & 0x7FFFFFFF;
		offset += 8;

		HuffLZ decompressor(length, offset);
		const char *buffer = 0;

		FileStreamWriter fileStreamWriter(pathOut);

		do
		{
			buffer = decompressor.GetInternalBuffer(&length);
			fileStreamWriter.Write(buffer, length);
		} while (length);
	}
	catch (std::exception e)
	{
		throw std::runtime_error("Error attempting to extract LZH compressed file " + pathOut + ". Internal Error Message: " + e.what());
	}
}
```

**Comment by DanRStevens** [comment]
Looks like we are missing some support infrastructure that would help fix or easily work around this bug.

The `HuffLZ` class is similar to a `StreamReader`, but isn't. Internally it makes use of a `BitStream` class, which is also similar to a `StreamReader` but isn't, and shouldn't be since it works with bits, not bytes. I think we should have a HuffLZStreamReader class, that provides output in a manner consistent with the `StreamReader` interface. We might still make use of an internal `BitStream` class, however, the input to the `BitStream` class could come from a `StreamReader` object, rather than just a flat memory buffer. That would allow things to compose in a much more flexible manner.

For now, an easy solution would be similar to code that was recently removed, where we size a `vector` to hold all data, and use that as a memory buffer. At least then we have working code in the meantime.

**Comment by Brett208** [comment]
Yeah, this issue was to fix the immediate bug. 

Do we want to eventually refactor and move BitStream into the streams code? Maybe a better question is should the Stream code support a generic BitStream class or is the idea of a BitStream too specific or rare of a use case for a Stream library? I've never really used one before.

I'd like to discuss in a dedicated thread how we want to standardize handling of compression and decompression of streams for the streams library. @ldicker83 mentioned that it was sort of a missing feature back in the forums. A topic that probably needs to percolate for a while.

**Comment by DanRStevens** [comment]
I think BitStream might be sufficiently different so as to not include it. Maybe we can throw it in later, but I'd want to do some heavy code reviews and get feedback from at least a couple other programmers on that first. I don't think the current design has received as much thought or attention as the other stream classes.

You'd also be correct in pointing out that it's more of a rare case. It could be a common tool for compression related streams, but probably not much use outside of that.

Perhaps we can revisit the notion of a BitStream after we've addressed other issues. In particular, fixing this code, and then perhaps upgrading the code to be more Stream conforming.
